on: [push]

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:latest
    steps:
    - uses: actions/checkout@v2
    - name: Package
      run: /usr/local/bin/entrypoint.sh WonderlandEditor --windowless --package --project TestAR.wlp --credentials "$WLE_CREDENTIALS"
      env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
          FIREBASE_APIKEY: ${{ secrets.FIREBASE_APIKEY }}
    - name: Gzip
      run: gzip -k deploy/*
    - name: Upload package artifact
      uses: actions/upload-artifact@v2
      with:
        name: Project-deploy
        path: deploy/
  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download package artifact
      uses: actions/download-artifact@v2
      with:
        name: Project-deploy
        path: deploy
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: deploy
